name: Vérification arborescence

on:
  pull_request:
    branches:
      - master

jobs:
  check_structure:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout du code
        uses: actions/checkout@v4

      - name: Vérification de l'arborescence
        run: |
          echo "Vérification de l'arborescence..."
          tree -d
          if [ ! -d "site/img" ] || [ ! -d "site/css" ] || [ ! -d "site/js" ] || [ ! -d "src" ]; then
            echo "Erreur: L'arborescence ne respecte pas la structure attendue."
            exit 1
          fi
        
      - name: Vérification des types de fichiers
        run: |
          echo "Vérification des types de fichiers..."
          find site -type f ! \( -name "*.html" -o -name "*.php" \) | grep . && exit 1 || echo "OK: site"
          find site/img -type f ! \( -name "*.png" -o -name "*.jpg" \) | grep . && exit 1 || echo "OK: img"
          find site/css -type f ! -name "*.css" | grep . && exit 1 || echo "OK: css"
          find site/js -type f ! -name "*.js" | grep . && exit 1 || echo "OK: js"