name: Vérification de l'arborescence

on:
  pull_request:
    branches:
      - main

jobs:
  check-arbo:
    name: Vérification de l'arborescence
    runs-on: ubuntu-latest
    steps:
      - name: Checkout du code
        uses: actions/checkout@v4

      - name: Vérifier l'arborescence
        run: |
          echo "📂 Vérification de l'arborescence..."
          tree -d
          
          # Vérifier que les dossiers existent
          if [ ! -d "site" ] || [ ! -d "site/img" ] || [ ! -d "site/css" ] || [ ! -d "site/js" ] || [ ! -d "src" ]; then
            echo "❌ Erreur: Certains dossiers sont manquants !"
            exit 1
          fi

          # Vérifier les extensions
          if find site ! -name "*.html" ! -name "*.php" -type f | grep .; then
            echo "❌ Erreur: 'site' ne doit contenir que .html ou .php"
            exit 1
          fi
          if find site/img ! -name "*.png" ! -name "*.jpg" -type f | grep .; then
            echo "❌ Erreur: 'img' ne doit contenir que .png ou .jpg"
            exit 1
          fi
          if find site/css ! -name "*.css" -type f | grep .; then
            echo "❌ Erreur: 'css' ne doit contenir que .css"
            exit 1
          fi
          if find site/js ! -name "*.js" -type f | grep .; then
            echo "❌ Erreur: 'js' ne doit contenir que .js"
            exit 1
          fi

          echo "✅ Vérification réussie !"
