name: CI - Lint et Vérification

on: 
  [push, pull_request]

jobs:
  lint-php:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4.5'
          tools: phpcs, phpunit

      - name: Change permissions for PHPCS
        run: chmod +x vendor/bin/phpcs

      - name: Debug - Vérifier PHPCS
        run: which phpcs || echo "PHPCS non trouvé"

      - name: List files
        run: ls -la

      - name: Install dependencies
        run: composer install --no-progress --no-suggest

      - name: Run PHPCS
        run: vendor/bin/phpcs --standard=PSR12 src/ || echo "PHPCS n'a pas pu s'exécuter"

      - name: Auto-fix issues with PHPCBF
        run: vendor/bin/phpcbf --standard=PSR12 src/ || echo "PHPCBF n'a pas pu s'exécuter"

      - name: Run PHPUnit tests
        run: vendor/bin/phpunit
