name: CI - Lint et Vérification

on: 
  [push, pull_request]

jobs:
  lint-php:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4.5'
          tools: phpcs, phpunit

      - name: Install dependencies
        run: composer install --no-progress --no-suggest

      - name: Install PHPCS globally
        run: composer global require squizlabs/php_codesniffer

      - name: Add Composer global bin to PATH
        run: echo "::add-path::$(composer global config --absolute home)/vendor/bin"

      - name: Run PHPCS
        run: phpcs --standard=PSR12 src/  # Vérifie la conformité du code

      - name: Run PHPUnit tests
        run: vendor/bin/phpunit --coverage-html coverage  # Exécute les tests et génère un rapport de couverture
